### ISSUE TITLE
Images in Google Drive Picker return 403 error on preview

### ISSUE THREAD

**Issue by chemitaxis** [googleworkspace/drive-picker-element#28]
Hi team,

First, thank you for the great work on the Google Drive Picker web component! I'm currently testing it and encountered an issue related to image previews.

When trying to preview some images using the Google Drive Picker, the request for the image files returns a 403 Forbidden error. This behavior is inconsistent as some images load without issues, while others fail.

Steps to reproduce:
Integrate the Google Drive Picker web component into a web application as per the documentation.
Open the Picker and select an image file for preview.
Notice that some image previews fail to load, showing a 403 error in the browser's developer console.
Expected behavior:
All accessible images should load correctly in the preview without throwing a 403 error.

Actual behavior:
Some image files return a 403 error when attempting to preview them, making the feature unreliable.

Additional context:
The issue might be related to file permissions or the way the component handles access tokens.
Tested in Chrome Version 131.0.6778.140 (Official Build) (arm64)
The drive.file scope was used during testing.
Please let me know if there's additional information I can provide or if there's a workaround for this issue.

Thanks again for your efforts!

**Comment by jpoehnelt** [comment]
This is expected given https://issuetracker.google.com/208855070?

I don't believe this is related to the web component wrapping the library. Going to close with this assumption, but comment here if this is not the case.

Thanks!
